optimize scale-up and delete new node
sealerio/sealer pull request #2185
Opened 2023-04-13 08:40 UTC by wizardlyk

### Describe what this PR does / why we need it
scale-up/delete new node will not depend on all existing node is reachable.

### Does this pull request fix one issue?
Fixes #1998

### Describe how you did it

### Describe how to verify it

### Special notes for reviews

2023-04-13 10:07 UTC, Stevent-fei commented
learned, very strong🐂🍺

2023-04-13 10:07 UTC, Stevent-fei reviewed
lgtm

2023-04-13 10:09 UTC, Stevent-fei approved these changes

2023-04-14 02:53 UTC, Stevent-fei commented
When deleting the cluster, you should also skip the missing node, otherwise an error will occur?
```shell
[ERROR] [root.go:75] sealer-unknown: [ssh][172.16.130.25] failed to create ssh session: dial tcp 172.16.130.25:22: i/o timeout
```

2023-04-14 12:18 UTC, cubxxw reviewed
LGTM

2023-04-14 12:19 UTC, cubxxw approved these changes

2023-04-17 07:25 UTC, VinceCui commented
以下几个问题:configureLvs

2023-04-17 07:32 UTC, VinceCui requested changes

2023-04-17 07:32 UTC, VinceCui commented on pkg/registry/local.go
> +				} else if strings.Contains(err.Error(), "unable to authenticate") {
这里有问题，首先，这里不应该走到ssh旧节点的逻辑，其次，ssh新节点时，如果密码失败，此处应该报错。

2023-04-17 08:53 UTC, wizardlyk commented
> 

1. configurelvs调用，发生在install、scale-up、delete、upgrade、rollback这些command中；install保持不变，scale-up和delete增加判断 master节点有没有新增/减少，upgrade、rollback则不执行configurelvs。
2.  扩容时只有configurelvs在ssh旧节点。

2023-04-18 02:56 UTC, kakaZhou719 commented
> 

1. 只扩容master时候，需要在旧的node节点上更新 新的LVS real server endpoint（新master ip），需要连通旧节点。
2. 只扩容node的时候，需要在新的node节点上配置，lvs规则，无需连通旧节点。
3. 同时扩容master和node的时候，那么新节点，旧节点就同时都需要连通。

2023-04-28 08:41 UTC, VinceCui approved these changes
LGTM

2023-04-28 08:41 UTC, merged